#!/usr/bin/env dash

hyprctl -j clients | jq --argjson id "$(hyprctl -j activeworkspace | jq -r '.id')" -r '.[] | select(.workspace.id == $id) | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp -r -b '#00000000' -s '#FFFFFF1A' -B '#00000000' -c '#FFFFFFFF'
